# Generated by Django 4.2.7 on 2023-11-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': ' Usuarios'},
        ),
    ]
