# Generated by Django 4.2.7 on 2023-11-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuario',
        ),
    ]
