# Generated by Django 4.2.7 on 2023-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
